# Generated by Django 5.2.3 on 2025-06-16 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('tipo_ativo', models.CharField(choices=[('VEICULO', 'Veículo'), ('MOTOR', 'Motor'), ('OUTROS', 'Outros')], default='OUTROS', max_length=10, verbose_name='Tipo de Ativo')),
                ('data_fabricacao', models.DateField(blank=True, null=True, verbose_name='Data de Fabricação')),
                ('data_aquisicao', models.DateField(verbose_name='Data de Aquisição')),
                ('tipo_contador_principal', models.CharField(choices=[('HODOMETRO', 'Hodômetro'), ('HORIMETRO', 'Horímetro')], max_length=10, verbose_name='Tipo de Contador Principal')),
                ('hodometro_inicial', models.FloatField(default=0, verbose_name='Hodômetro Inicial/Atual')),
                ('horimetro_inicial', models.FloatField(default=0, verbose_name='Horímetro Inicial/Atual')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
            ],
            options={
                'verbose_name': 'Ativo',
                'verbose_name_plural': 'Ativos',
            },
        ),
        migrations.CreateModel(
            name='ManutencaoProgramada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_programada', models.DateField(verbose_name='Data Programada')),
                ('tipo_manutencao', models.CharField(choices=[('PREVENTIVA', 'Preventiva'), ('CORRETIVA', 'Corretiva'), ('PREDITIVA', 'Preditiva')], max_length=15, verbose_name='Tipo de Manutenção')),
                ('servico', models.CharField(max_length=255, verbose_name='Serviço a ser executado')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('PROGRAMADA', 'Programada'), ('EM_ANDAMENTO', 'Em Andamento'), ('IMPEDIDA', 'Impedida'), ('EXECUTADA', 'Executada')], default='RASCUNHO', max_length=15, verbose_name='Status')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes_programadas', to='manutencao_app.ativo', verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Manutenção Programada',
                'verbose_name_plural': 'Manutenções Programadas',
            },
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data de Abertura')),
                ('servico', models.TextField(verbose_name='Serviço Executado')),
                ('hodometro_atual', models.FloatField(verbose_name='Hodômetro na Execução')),
                ('horimetro_atual', models.FloatField(verbose_name='Horímetro na Execução')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico', to='manutencao_app.ativo', verbose_name='Ativo')),
                ('manutencao_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordem_servico_executada', to='manutencao_app.manutencaoprogramada', verbose_name='Manutenção de Origem')),
            ],
            options={
                'verbose_name': 'Ordem de Serviço',
                'verbose_name_plural': 'Ordens de Serviço',
                'ordering': ['-data'],
            },
        ),
    ]
